### ISSUE TITLE
[Final Fantasy XIV] Does not deactivate when other window gets focus

### ISSUE THREAD

**Issue by Ceiyne** [SpecialKO/SpecialK#10]
I have been using Special K version 22.3.11.3 with FFXIV for a couple months now with zero issues. I'm not doing anything fancy, just using it as a frame limiter and for getting g-sync in a borderless window.

Today I tried upgrading Special K, and now when I alt-tab out of FFXIV the window doesn't actually lose focus, so it keeps running at full FPS and with all sounds on. I tested with versions 22.5.30, 22.6.22 and 22.6.30, and the behavior was the same. I know there's a way to limit FPS and mute sound of an inactive window with Special K, and those do still work with FFXIV.  However, I'd prefer to do those things from the game because the game lets you configure certain sounds to come through even when not in focus.

In Special K, "Continue Rendering" is disabled, and I don't have anything else enabled that looks like it would cause this.  If I switch back to 22.3.11.3 alt-tab starts working normally again with the same config. 

The only set-up that I could find to make it work as expected was to have SK force the game into a window (i.e., with title bar, etc.) and then it would deactivate properly. But obviously this kind of defeats the purpose.

I tried the following troubleshooting steps suggested on Discord but they didn't fix the issue:

- Tried both local and global injection (I normally use local, but global behaved the same in all tests below)
- Resetting my SK ini file by deleting it
- Confirmed the in-game config is still set to Borderless Window
- Tested with another game (Diablo 3) and confirmed it properly loses focus when another window gets focus (so this problem seems exclusive to FFXIV)
- Tried adjusting my SK ini to several suggested alternatives:

(1)
[Display.Output]
ForceWindowed=true

[Window.System]
Borderless=true
Center=true
RenderInBackground=false
AlwaysOnTop=2

(2)
[Display.Output]
ForceWindowed=true

[Window.System]
Borderless=true
Center=true
RenderInBackground=false
AlwaysOnTop=-1

(3)
[Display.Output]
ForceWindowed=true

[Window.System]
Borderless=true
Center=true
RenderInBackground=false
AlwaysOnTop=0

**Comment by Aemony** [comment]
> I know there's a way to limit FPS and mute sound of an inactive window with Special K, and those do still work with FFXIV. However, I'd prefer to do those things from the game because the game lets you configure certain sounds to come through even when not in focus.

So you mean that **SK** is aware that the game has lost focus, but the game itself is not?

**Comment by Ceiyne** [comment]
> So you mean that SK is aware that the game has lost focus, but the game itself is not?
As far as I can tell, yes, because the mute and reduced FPS options in SK do work with FFXIV whereas the ones built into the game do not.

**Comment by Ceiyne** [comment]
This is still an issue with SpecialK v 22.9.26 and SKIF v 0.9.10 (Oct 5 2022). Tested with a fresh SpecialK.ini (not my old one from the earlier version of SpecialK).

Some other weirdness, including a clunky workaround:

- My FFXIV in-game settings specify "Borderless Window" and this works as expected when SpecialK is not injected. However, when I started the game with a fresh SpecialK.ini, the game appeared in a bordered window. This continues unless I apply window type and resolution overrides in SpecialK. (This happened in the old version of SpecialK, too.)
- If I change the in-game settings to either Windowed or Full Screen, and then change them back to Borderless Window, the game properly displays in a Borderless Window instead of the bordered one.  In addition, at this point the game DOES properly detect when it loses focus.

Note: Since I originally opened this issue, I did a full uninstall/reinstall of FFXIV. So, since this issue still exists, that seems to rule out the possibility of something corrupted/funky with my FFXIV installation.

**Comment by Ceiyne** [comment]
After entering the last comment, I played around with delaying global injection for the game, but it didn't fix the issue. If I injected it late enough to prevent the game from going into a window, then it didn't run with G-SYNC. If I injected it earlier, then it ended up in a window.

If the problem where FFXIV goes into a bordered window for no reason could be fixed, that would take care of the issue with loss of focus. I'm only getting the issue with no loss of focus when I apply window & resolution overrides in SpecialK (which is needed to avoid the workaround of manually setting/resetting options in-game to get it back in a window).

**Comment by MiKE41** [comment]
After doing some digging, it seems that FFXIV relies on the WM_NCACTIVATE message to determine if the game is in the background or not, and the code at https://github.com/SpecialKO/SpecialK/commit/651eefcc25bdadcda36112d2b19196f8f7c7bf47#diff-b0f3940fc8077de17e026c472533a7f495580334f015a16e2ea41a6da858535fR5282 appears to be stopping this message from getting to the game.

Michael

**Comment by MiKE41** [comment]
https://github.com/SpecialKO/SpecialK/commit/c1a3ab5e1ab088b401ab60a5864e33fea0b4f9ba 

The changes made in this commit fix this issue. I believe this issue can be closed.

**Comment by Aemony** [comment]
Ah, great to hear that!
