### ISSUE TITLE
DLSS crashes in SK when forcing DLAA and mode is set to ultra performance

### ISSUE THREAD

**Issue by adamnorbacker** [SpecialKO/SpecialK#109]
Game: Assassins creed mirage

Set ingame to ultra performance.

Leave ingame menu and close it so you can play. 
Open SK, force DLAA and bug happens.

Creates nasty artifacts on screen and DLSS section on SK is removed.

**Comment by Kaldaien** [comment]
Ships with a DLSS DLL version < 3.1.13, so doesn't have a DLAA quality level.
Problem's fixed in SK 23.10.11.1
