### ISSUE TITLE
(One more Question please) How to switch to one of the textures in a shader like in "Live RenderTarget View"?

### ISSUE THREAD

**Issue by 4Brad-23** [SpecialKO/SpecialK#115]
Like here:
https://steamuserimages-a.akamaihd.net/ugc/2431257084892995384/D14BC194EF584DEDAE8A0CCADED5F80B9AAE49A9/

For instance, there's a texture in one of these that could turn the whole shader of the game to normal maps/textures only.

Thank you.

**Comment by Aemony** [comment]
Note the texture hash that's mentioned besides it, then go through the list of textures and locate that one, I guess?

**Comment by 4Brad-23** [comment]
> Note the texture hash that's mentioned besides it, then go through the list of textures and locate that one, I guess?

I appreciate the responses - but would me finding it in the texture list be toggle-able as a shader? because I did and it shows a preview of what I want but won't let me do anything besides viewing it in its small preview window!

Please tell me it's possible. thank you.

**Comment by Kaldaien** [comment]
You can right-click pixel shaders and disable individual textures they use. It gets real tedious, but that's the only option you've got.

Wow is that screenshot old :)

**Comment by 4Brad-23** [comment]
Yeah, the screenshot is not mine just for reference - But still, it won't let me navigate through all of them and they have different Hashes/IDs... for instance, it says there are 13 textures but only shows 2 on the "right-click"!

**Comment by 4Brad-23** [comment]
Can I use any of the output of individual render passes in "Live RenderTarget View" or are they there just for preview?
