### ISSUE TITLE
23.10.30 Introduced problem with Reshade on SDR screen.

### ISSUE THREAD

**Issue by Maruzeru** [SpecialKO/SpecialK#117]
I am playing Witcher 3 on dx12 and since this (23.10.30 - 23.10.31.2) update the screen is darkened like there is some HDR mismatch between reshade and special k (I am playing in SDR with no HDR enabled anywhere). If I turn off the reshade shader it goes back to normal. Toggling between "draw Reshade first" changes if the SK overlay is darkened or not.

![witcher3 2023-11-01 07-06-50](https://github.com/SpecialKO/SpecialK/assets/138612504/a70d2f3c-0aa1-4d8f-bd84-07848619f3a4)
![witcher3 2023-11-01 07-06-46](https://github.com/SpecialKO/SpecialK/assets/138612504/59dddb0e-a1aa-4b18-b3b1-a4a870c48965)
![witcher3 2023-11-01 07-07-07](https://github.com/SpecialKO/SpecialK/assets/138612504/2cebad15-a7d1-4c66-a076-f028eea386c8)

**Comment by Kaldaien** [comment]
This is normal, ReShade mode effectively behaves the same as loading ReShade "lazy". That's no longer ideal now that SK can control if ReShade draws before or after SK using an add-on feature.

I will be removing "ReShade mode" altogether in the future. If you use that, ReShade will post-process its own UI. It could potentially apply post-processing twice, in fact.

**Comment by Maruzeru** [comment]
I am only using a simple sharpening filter (immerse sharpen). That isn't supposed to darken the screen even if applied twice. What can I do to remove this darkening?
Now I can't use new SK versions with reshade because of this. I cannot disable this darkening anywhere.
What am I supposed to do if this is normal?
I have ReshadeMode=false in config.

**Comment by Maruzeru** [comment]
As of the latest version (23.11.5.1). The issue seems to be fixed. Thank you!
