### ISSUE TITLE
Tactics Ogre Reborn not playable with recent builds - found reason

### ISSUE THREAD

**Issue by mzino** [SpecialKO/SpecialK#127]
Using the most recent builds of SK, Tactics Ogre Reborn crashes upon triggering pre-rendered cutscenes (.pmf movies). There is one at game startup that is unskippable, so the game is effectively unplayable with SK.

The latest nightly build that works is 23.7.4.1, and I managed to pinpoint the exact file change that causes these crashes to happen.

Commit is 20a2286, and the culprit is the change in debug_utils.cpp. Reverting that single change as per 25989c7 results in a [working 23.12.16.4 build](https://github.com/mzino/SpecialK/actions/runs/7231716113) that renders the Tactics Ogre cutscenes without crashing.

Can this be fixed on the main branch so that support for the game is restored in the official builds?

**Comment by Kaldaien** [comment]
Should be fixed in 23.12.17
