### ISSUE TITLE
[Hatsune Miku: Project DIVA Mega Mix+] Framerate unlocker no longer works after the 1.02 update

### ISSUE THREAD

**Issue by Braasileiro** [SpecialKO/SpecialK#13]
Description:
After the update the framerate unlocker is not working as it should. It's getting a maximum of 65 fps in menus and gameplay. At least in my case.
Limiting any number below 65 still works normally.

Steps to reproduce:
1. Launch the game with local install of SpecialK (22.7.19).
2. Disable VSync and Framerate Limiter.

Thanks in advance.

**Comment by Kaldaien** [comment]
Yeah, I will have to find the updated memory addresses. I also need to remove their broken Windows 10 version check code again, lol.
