### ISSUE TITLE
NierR Replicant ver.sqrt(1.5) 1.0.0.3 broken since commit ad40030 ("Add Aspect Ratio Unlock for Star Ocean 2")

### ISSUE THREAD

**Issue by ReneHollander** [SpecialKO/SpecialK#131]
NieR Replicant ver.sqrt(1.5) 1.0.0.3 is broken since https://github.com/SpecialKO/SpecialK/commit/ad40030c5d6421d2fdc2a24c5ab57f1da935b6a8. Found via manual bisection using binaries built by the GH Action:
- Working:
  - Commit: https://github.com/SpecialKO/SpecialK/commit/d9e08c579d6d579c5571a1a34520a08a68261028
  - Build: https://github.com/SpecialKO/SpecialK/actions/runs/7231029403
  - Screenshot: 
![Screenshot from 2024-01-06 17-41-16](https://github.com/SpecialKO/SpecialK/assets/5379596/69aede0a-1db9-4c5c-9ea0-5dabe4198910)

- Broken:
  - Commit: https://github.com/SpecialKO/SpecialK/commit/ad40030c5d6421d2fdc2a24c5ab57f1da935b6a8 
  - Build: https://github.com/SpecialKO/SpecialK/actions/runs/7236895517
  - When launching via steam no window ever opens. Seems like the process crashes very early on and then doesn't terminate correctly for whatever reason (process `50918` is a zombie process):
    ```
    % ps -aux | grep NieR           
    rene       50222  0.0  0.0  28112  5836 ?        S    17:45   0:00 /home/rene/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1113560 -- /home/rene/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- /home/rene/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper/_v2-entry-point --verb=waitforexitandrun -- /home/rene/.local/share/Steam/steamapps/common/Proton 8.0/proton waitforexitandrun /home/rene/.local/share/Steam/steamapps/common/NieR Replicant ver.1.22474487139/NieR Replicant ver.1.22474487139.exe
    rene       50223  0.1  0.0   4596  1120 ?        S    17:45   0:00 /home/rene/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper/pressure-vessel/bin/pv-bwrap --args 30 /usr/lib/pressure-vessel/from-host/bin/pressure-vessel-adverb --generate-locales --fd 19 --regenerate-ld.so-cache /run/pressure-vessel/ldso --add-ld.so-path /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu --add-ld.so-path /usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu --set-ld-library-path /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/aliases:/usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/aliases --exit-with-parent --subreaper --assign-fd=1=6 --assign-fd=2=7 --shell=none --terminal=none --ld-preload=/home/rene/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so --ld-preload=/home/rene/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so -- /home/rene/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper/pressure-vessel/bin/steam-runtime-launcher-interface-0 container-runtime /home/rene/.local/share/Steam/steamapps/common/Proton 8.0/proton waitforexitandrun /home/rene/.local/share/Steam/steamapps/common/NieR Replicant ver.1.22474487139/NieR Replicant ver.1.22474487139.exe
    rene       50312  0.0  0.0  30404  5436 ?        Ss   17:45   0:00 /usr/lib/pressure-vessel/from-host/bin/pressure-vessel-adverb --generate-locales --fd 19 --regenerate-ld.so-cache /run/pressure-vessel/ldso --add-ld.so-path /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu --add-ld.so-path /usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu --set-ld-library-path /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/aliases:/usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/aliases --exit-with-parent --subreaper --assign-fd=1=6 --assign-fd=2=7 --shell=none --terminal=none --ld-preload=/home/rene/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so --ld-preload=/home/rene/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so -- /home/rene/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper/pressure-vessel/bin/steam-runtime-launcher-interface-0 container-runtime /home/rene/.local/share/Steam/steamapps/common/Proton 8.0/proton waitforexitandrun /home/rene/.local/share/Steam/steamapps/common/NieR Replicant ver.1.22474487139/NieR Replicant ver.1.22474487139.exe
    rene       50345  0.0  0.0 121320 55596 ?        S    17:45   0:00 python3 /home/rene/.local/share/Steam/steamapps/common/Proton 8.0/proton waitforexitandrun /home/rene/.local/share/Steam/steamapps/common/NieR Replicant ver.1.22474487139/NieR Replicant ver.1.22474487139.exe
    rene       50372  0.0  0.2 2229524 168072 ?      Sl   17:45   0:00 c:\windows\system32\steam.exe /home/rene/.local/share/Steam/steamapps/common/NieR Replicant ver.1.22474487139/NieR Replicant ver.1.22474487139.exe
    rene       50918  0.0  0.0      0     0 ?        Zl   17:45   0:00 [NieR Replicant ] <defunct>
    rene       56128  0.0  0.0   6908  2660 pts/1    S+   17:49   0:00 grep --color=auto NieR
    ```
    - The SpecialK `logs` directory only has a crash file containing 3 bytes: 
    ```
    hexdump -C '/home/rene/.local/share/Steam/steamapps/common/NieR Replicant ver.1.22474487139/logs/crash.log' 
    00000000  ef bb bf                                          |...|
    00000003
    ```

Tried with following Proton versions, all behave the exact same:
- Latest Proton-GE (8.25)
- Proton Experimental
- Proton 8.0-4

Specs:
- No funky DXVK configs or options - all defaults everywhere
- Using Arch btw
- LTS Kernel (`6.1.70-1-lts`)
- CPU: AMD 5900X
- GPU: AMD 7900XTX
- RAM: 64GB

Also same behavior with both https://github.com/SpecialKO/SpecialK/commit/a98af929bc3698ca19c5ee31319055ccb5e882cb and https://github.com/SpecialKO/SpecialK/commit/7e5d208d6298d93c7d18acf550349e1ad7578e8c (which obviosuly are the versions of SpecialK I am trying to get working). https://github.com/SpecialKO/SpecialK/commit/7e5d208d6298d93c7d18acf550349e1ad7578e8c I also got working on Windows 10 without problems (but I would prefer playing the game on Linux to avoid rebooting)

Looking at the commit in question I don't see anything that would break the game in such a way. I was hoping for something more obvious to go off of, but I think I need some pointers before spending too much time trying to get custom builds of SpecialK compiled...

**Comment by Kaldaien** [comment]
This is weird. Are you positive that's the exact build with the problem?

I'm going to have a hell of time debugging this without any SK logs :-\ Steam Deck's kind of a pain, I have one I guess I could boot it up and look into it if I can find the damn thing.

**Comment by ReneHollander** [comment]
Tested again with latest build today (https://github.com/SpecialKO/SpecialK/commit/b7e81a8c337bc5e1df4a33fbbe64251751876619) and it works again. Sorry for not debugging earlier - didn't get to continue playing NieR...
