### ISSUE TITLE
No Input In Games Using Guitar Hero Guitar on SK v24.1.7.4 Forward

### ISSUE THREAD

**Issue by flash1228** [SpecialKO/SpecialK#132]
I posted in the Discord support channel and was recommend to post an issue here.

Since 24.1.7.4 using Special K in Clone Hero or YARG my PS3 Guitar Hero World Tour Guitar controller sends no input to the games. Rolling back to 24.1.6 resolves the issue and it works fine again.

I'm just guessing, but I'm thinking the issue with my guitar hero controller might be due to it not having an actual d-pad and is weird the way it's buttons are represented in Windows so maybe it's getting caught by the below change. However, I could be totally wrong as to the cause of it, but it seemed to make the most sense.

"+ [24.1.7.4] Filter WinMM Joystick devices that lack D-Pad and at least 4 buttons from being seen by games, as often they will interpret dwPOV == 0 as D-Pad UP when polling devices that have no D-Pad!"

**Comment by Kaldaien** [comment]
Does the "WinMM Joystick" activity indicator light up in the control panel? If it doesn't then there's something else going wrong.

**Comment by Kaldaien** [comment]
Can you try this version and report back? I've altered the filtering logic, and also added any filtered devices to Special K's logs.

[SpecialK.zip](https://github.com/SpecialKO/SpecialK/files/13878038/SpecialK.zip)

**Comment by flash1228** [comment]
I tried that and have the same result. Here are the logs from Special K\Profiles\YARG.exe
[logs.zip](https://github.com/SpecialKO/SpecialK/files/13878166/logs.zip)

**Comment by Kaldaien** [comment]
I don't see anything unusual in the YARG logs, but Clone Hero is using Raw Input on an HID usage (0x8 - "Multi-axis Controller") that Special K's never encountered before. I think those log entries are harmless though, that just means SK's going to ignore those devices.

Have you tried the "compatibility profile" in SKIF?

Right-click `Special K.ini` and there's an option that will clear the game's INI and turn off nearly every input API that SK deals with. The new WinMM stuff is not included, but as far as I can tell, neither game uses that API.

**Comment by flash1228** [comment]
It does work with v24.1.9.1 when I use the compatibility profile. Here are the logs again if it's helpful
[logs.zip](https://github.com/SpecialKO/SpecialK/files/13888631/logs.zip)

**Comment by Kaldaien** [comment]
It should be fixed now without having to use the compatibility profile.

**Comment by flash1228** [comment]
Awesome, it is working now with the latest discord build. Thank you!
