### ISSUE TITLE
[Genshin Impact] sRGB Bypass does not work in newer versions of SK

### ISSUE THREAD

**Issue by LiuQixuan** [SpecialKO/SpecialK#14]
- Special K version: 22.6.30.1
- Game: Genshin Impact 2.8.0

- Problem Description:
  After using special k, the display is abnormal, the viewport seems to be covered with a layer of fog, and the brighter tones.

- appendix:
  **Abnormal display effect:**
  ![Abnormal][plink1]

  <br/>

  <br/>

  **Normal display effect:**
  ![Normal][plink2]

- Hope for help:
  How to set it to display normally or how to reset default configuration to display normally.

[plink1]:https://github.com/LiuQixuan/ImageHostingService/blob/main/ImageHostingForIssues/SpecialK/abnormal.jpg?raw=true
[plink2]:https://github.com/LiuQixuan/ImageHostingService/blob/main/ImageHostingForIssues/SpecialK/normal.jpg?raw=true

**Comment by marat569** [comment]
You need an older version of SK for genshin, specifically 22.4.9.1

Download it here: [https://cdn.discordapp.com/attachments/792979353117524009/961821541878886420/SpecialK.7z](https://cdn.discordapp.com/attachments/792979353117524009/961821541878886420/SpecialK.7z)

If you're using SKIF you can just replace the .dll files; or just local inject them.

**Comment by LiuQixuan** [comment]
> You need an older version of SK for genshin, specifically 22.4.9.1
> 
> Download it here: https://cdn.discordapp.com/attachments/792979353117524009/961821541878886420/SpecialK.7z
> 
> If you're using SKIF you can just replace the .dll files; or just local inject them.
> 
> If using SKIF, make sure to run SKIF as admin or use the "elevated privileges" box (still in beta)

![pic of screenshot](https://github.com/LiuQixuan/ImageHostingService/blob/main/ImageHostingForIssues/SpecialK/screenshot01.jpg?raw=true)
Thanks,but not work for me.

**Comment by marat569** [comment]
@LiuQixuan yes, you need to install the old version that I linked.

Anything else will not work.

**Comment by LiuQixuan** [comment]
> @LiuQixuan yes, you need to install the old version that I linked.
> 
> Anything else will not work.
> 
> Edit: SKIF's version does not work; you want an old version of SpecialK.dll (that I linked above)
> 
> You can replace the specialk .dll files in C:\Users[username]\Documents\My Mods\SpecialK [there should be a shortcut or folder] if you're using SKIF -- just replace the files there with the files above.
> 
> The picture above shows you are not using the right version, you need to be on version 22.4.9.1 [which again is the one I linked]

Sorry.I make mistake(a lots of files in download file). I tried again using the file you provided. Although the picture is no longer  covered with a layer of fog,but it becomes dark.

**appendix:**
![pic1](https://github.com/LiuQixuan/ImageHostingService/blob/main/ImageHostingForIssues/SpecialK/screenshot02.jpg?raw=true)
![pic2](https://github.com/LiuQixuan/ImageHostingService/blob/main/ImageHostingForIssues/SpecialK/screenshot03.jpg?raw=true)

**Comment by marat569** [comment]
You're fine, you're on the right version now c:

As for why the image is dark; I don't know -- I'll ask some other Genshin players and see if they can help out. 

You can try restarting the game a couple of times, and see if it works.

**Comment by LiuQixuan** [comment]
> You're fine, you're on the right version now c:
> 
> As for why the image is dark; I don't know -- I'll ask some other Genshin players and see if they can help out.
> 
> You can try restarting the game a couple of times, and see if it works.

OK, I will try a few more times. Thank you very much.

**Comment by marat569** [comment]
@LiuQixuan 

I asked some people genshin players on the SK discord, and the fix is to press Display, and set sRGB Bypass to "Passthrough", like in the picture below:

![image](https://user-images.githubusercontent.com/7017110/180591540-0dc48bfd-0794-4fbd-8322-e15e70aff9a6.png)

If you have any questions, feel free to join the discord; as you will get an instant response

[http://discord.gg/specialk](http://discord.gg/specialk)

**Comment by Aemony** [comment]
There were a few sRGB bundled changes in this commit which is most likely related to what's preventing newer versions of SK from applying the sRGB Bypass stuff:

https://github.com/SpecialKO/SpecialK/commit/c9b942f6b27774f7143f62baaf4341b491028c77

**Comment by LiuQixuan** [comment]
> @LiuQixuan
> 
> I asked some people genshin players on the SK discord, and the fix is to press Display, and set sRGB Bypass to "Passthrough", like in the picture below:
> 
> ![image](https://user-images.githubusercontent.com/7017110/180591540-0dc48bfd-0794-4fbd-8322-e15e70aff9a6.png)
> 
> If you have any questions, feel free to join the discord; as you will get an instant response
> 
> http://discord.gg/specialk

Thank you very much. I checked the settings, modified it according to your method, the problem is solved, everything works fine now.
I also saw other articles before saying that sRGB bypass was changed to strip, and I forgot to change it back.
I have only used SpecialK recently, and I will go to discord to communicate with other people and learn how to use it in the future.
Thanks.

**Comment by Aemony** [comment]
Oh, I forgot -- I'll leave this issue open to track the issue with the sRGB Bypass in newer versions of Special K. Hopefully we might solve that one so newer versions become compatible again.

**Comment by Spodi** [comment]
Wasn't this issue fixed long ago? It looks like I don't need an old version of SK anymore. And I don't see that mentioned anywhere 🤷‍♂️

**Comment by Aemony** [comment]
Maybe for Genshin Impact, but we've had other games where the sRGB Bypass ended up being an issue (e.g. Rise of the Tomb Raider in DX11 mode).

**Comment by Aemony** [comment]
We have a separate issue ticket for Rise of the Tomb Raider so closing this one.
