### ISSUE TITLE
Vulkan AMD?

### ISSUE THREAD

**Issue by Pednick** [SpecialKO/SpecialK#141]
Any chance of having support for Vulkan with AMD?

**Comment by Kaldaien** [comment]
It should already work for 64-bit games, I think their interop layer crashes for 32-bit games when last checked. Because SK's got some compatibility problems with 32-bit D3D12 code since there's virtually none of it in existence.

**Comment by Pednick** [comment]
> It should already work for 64-bit games, I think their interop layer crashes for 32-bit games when last checked. Because SK's got some compatibility problems with 32-bit D3D12 code since there's virtually none of it in existence.

Oh alright, I'll close this then.
