### ISSUE TITLE
local install MGSTPP error

### ISSUE THREAD

**Issue by Pednick** [SpecialKO/SpecialK#145]
When I set up a local install with renaming to d3d11.dll for Metal Gear Solid V - The Phantom Pain, I get this error when the game is launching:

err:   D3D11: GetImage: BufferId > 0 not supported

And it crashes and does not start.

**Comment by Kaldaien** [comment]
Use a newer version

**Comment by Pednick** [comment]
> Use a newer version

I have newest version, still crashing.
