### ISSUE TITLE
No paper white option in the newest version of Special K?

### ISSUE THREAD

**Issue by bluecat1024** [SpecialKO/SpecialK#157]
The available parameter in sliders are only max brightness and a few perceptual boost parameters now. And no documents teaching us how to tune those things to reach target brightness.

What should I do to get 1000 nits peak brightness with 300 nits paper white? The paper white parameter does not seem to work in the hdr config file.

Thanks so much.

**Comment by marat569** [comment]
The paper white setting has been deprecated about a year ago. It did not do what it was supposed to, and ended up just misleading people.

I suggest just using Preset 0 without any changes.

If you want to increase your peak to 1000, set `sdr to hdr gamma` to 1.0

If you're not happy with that, you're free to disable SK's HDR processing, and using a reshade shader to tonemap the final image (Pumbo's for example)

**Comment by bluecat1024** [comment]
Also, should perceptual boost be turned on for HDR presets in both cases?

**Comment by marat569** [comment]
You want PB on all the time

I suggest selecting preset 0, press reset to return it to its default settings .
