### ISSUE TITLE
Far Cry 5 (with Proton + DXVK) has alternating swapchain pointers during SK_D3D11_RenderCtx::init, causing init release loop

### ISSUE THREAD

**Issue by Kethen** [SpecialKO/SpecialK#168]
Continuation of https://github.com/SpecialKO/SpecialK/issues/167

Two alternating swapchain pointers were being fed to SK_D3D11_RenderCtx::init by Far Cry 5 with Proton + DXVK, causing init release loop and causes high pcie bandwidth usage

This issue was initially observed in [Far Cry 5](https://store.steampowered.com/app/552520/Far_Cry_5/) + Proton + DXVK, however while narrowing down the issue, I found that it does not happen in [Combat Master](https://store.steampowered.com/app/2281730/Combat_Master_Season_1/) + Proton + DXVK

Below attaches log from Far Cry 5 + Proton + DXVK (on SK https://github.com/Kethen/SpecialK/commit/53aa50f41f6a2333899cdc1a4225b3ed78d73a37)

[dxgi.log](https://github.com/SpecialKO/SpecialK/files/15065849/dxgi.log)

Would be interesting to see if this happens on windows as well, and if it does, does it produce as big of a performance hit over there as well

**Comment by Kaldaien** [comment]
Jeeze, it seems they're going out of their way to break software compatibility :(

Yeah, this is the same bug that makes SK not perform well on Steam Deck since several releases of Proton agao.

It's another thing I can't fix, but maybe you'll have some luck getting them to fix this, as well as their weird Present -> Present1 code.

**Comment by Kethen** [comment]
> Jeeze, it seems they're going out of their way to break software compatibility :(
> 
> Yeah, this is the same bug that makes SK not perform well on Steam Deck since several releases of Proton agao.
> 
> It's another thing I can't fix, but maybe you'll have some luck getting them to fix this, as well as their weird Present -> Present1 code.

For now, I'll dust off my windows vm to see if this Far Cry 5 thing happens on windows 11 d3d11 as well, since out of two games I've tested with Proton it only happened on one

As for the Present -> Present1 issue, as mentioned in the closed issue, if nothing breaks on DXVK side and gets https://github.com/doitsujin/dxvk/pull/3966 reverted, it should be fixed on Proton when that lands

**Comment by Kethen** [comment]
closing for now, should be fixed s of https://github.com/doitsujin/dxvk/pull/3968
