### ISSUE TITLE
Fallout: New Vegas issues

### ISSUE THREAD

**Issue by trudnorx** [SpecialKO/SpecialK#169]
SK inconsistently detects whether the Fallout: New Vegas window is in the background. Tested with OneTweak mod.

**Comment by giias** [comment]
why was that tested with onetweak mod ? isn't that unnecessary if you're using sk ?

**Comment by WallSoGB** [comment]
Special K covers all functionalities that OneTweak has, so they shouldn't be used together.

**Comment by Kaldaien** [comment]
> SK inconsistently detects whether the Fallout: New Vegas window is in the background. Tested with OneTweak mod.

I'm sure it does. The two pieces of software have overlapping functionality, but SK encompasses the whole of what OneTweak can do. Thus, compatibility really isn't a priority. The other software's unnecessary.
