### ISSUE TITLE
Broken Hardware Cursor in Noita

### ISSUE THREAD

**Issue by WynterFoxx** [SpecialKO/SpecialK#172]
Noita has a broken hardware cursor with Special K enabled, even after applying the compatibility profile. To be specific, transparency isn't applied to the texture(?), causing it to appear as a white square. However, it shows up normally in recordings, so I was forced to take a picture of it from my phone.
![image](https://github.com/SpecialKO/SpecialK/assets/33386865/dbd7c654-27a0-4433-90c3-36ae01cd0f74)

**Comment by marat569** [comment]
Weird, I'm a fellow Noita enjoyer, and my game looks perfectly fine

![YdFFbMF](https://github.com/SpecialKO/SpecialK/assets/7017110/867ddfe8-fbb0-4274-a6bc-ad642886dc9a)

Are you on the latest discord build? If not I suggest upgrading and trying that out.

I've played noita with SK for a long time, and never ran into an issue with it.

**Comment by WynterFoxx** [comment]
Okay, so I'm going to close this issue because I could have sworn I tested the game with Special K turned off, but it turns out I didn't and the issue persists without SK running at all! No idea what's causing this nonsense, but it isn't Special K. Sorry.
