### ISSUE TITLE
[ENHANCEMENT] Run Program When Whitelisted Game Starts

### ISSUE THREAD

**Issue by shinra358** [SpecialKO/SpecialK#188]
I would like to request the option to choose a user defined program to run when a whitelisted game runs. SK would then hard kill said program when exiting the game or when the game's process is no longer seen running. If game is ended with SK, program will hard die before process closes. When process is killed through outside means, SK immediately kills program. Would be able to choose commandline options like when adding games. checkboxes depicting whether or not to close the program before the game, or close the game before the program. User defined list of programs to do this.

**Comment by Aemony** [comment]
This is better handled through a custom batch or PowerShell script.

**Comment by shinra358** [comment]
How's a bat gonna recieve the variable to what's on the whitelist of SK?
What you're telling me to do is make a bat for 309478643760 games where only one block of code in SK can say, something on the whitelist is activated so launch the user defined program.

**Comment by Aemony** [comment]
That's a concern of yours -- not ours, though I can mention that a typical solution would just be to have SKIF launch that custom batch file of yours which would then do the desired prerequisites, start the game, then idle until the game is closed or whatever, and then close it again.

Anyway, this is not something that we are interested in exploring or implementing.
