### ISSUE TITLE
Starting from version 24.9.23 (including 24.9.23), certain games using the DXVK patch are unable to run.

### ISSUE THREAD

**Issue by Kud-Fountain** [SpecialKO/SpecialK#203]
I tried two games, but neither of them could be successfully launched (the window froze and could only be ended by terminating the process). The two games are **Left 4 Dead 2** and **Team Fortress 2 (64bit)** (Note: I used this version of [DXVK](https://gitlab.com/Ph42oN/dxvk-gplasync) to improve the performance of these two games. However, the same result occurs even when using the official version of DXVK.). Below is the log for **Left 4 Dead 2**.

[game_output.log](https://github.com/user-attachments/files/17116816/game_output.log)
[modules.log](https://github.com/user-attachments/files/17116819/modules.log)
[SpecialK.log](https://github.com/user-attachments/files/17116820/SpecialK.log)
[steam_api.log](https://github.com/user-attachments/files/17116821/steam_api.log)
[crash.log](https://github.com/user-attachments/files/17116822/crash.log)
[dxgi_budget.log](https://github.com/user-attachments/files/17116823/dxgi_budget.log)

Specs:
* CPU: AMD Ryzen 7950X3D
* GPU: Nvidia GeForce RTX 4090
* SYSTEM: Windows 11 Insider Preview 10.0.22635.4145 (Beta)

**Comment by Kaldaien** [comment]
Hmm...

> Removing Redirection Bitmap from Flip Model Window

I think I see the problem, I have released 24.9.24.2 with that code removed.

[SpecialK64.zip](https://github.com/user-attachments/files/17118763/SpecialK64.zip)

Try that, please.

**Comment by Kud-Fountain** [comment]
The issue has been resolved after the update, thank you for the fix. I will close this issue now.
