### ISSUE TITLE
Special K freezes Steam Deck

### ISSUE THREAD

**Issue by SaltyBet** [SpecialKO/SpecialK#204]
SteamOS stable on Steam Deck.

When trying to inject Special K using dxgi.dll, game becomes laggy and the Deck Freezes; have to hard-reset.

Tried both default INI and sledgehammer INI.

Logs: [Archive.zip](https://github.com/user-attachments/files/17125319/Archive.zip)

**Comment by Kaldaien** [comment]
Doesn't surprise me.
I had to do all kinds of things to disable Steam Input in that game to make it work correctly. Valve thoroughly broke PlayStation controllers.

**Comment by Sangeki** [comment]
With anything newer than Proton 9.0-2 Special K causes RAM to fill up to exhaustion on startup. 9.0-3 was recently promoted form RC and is probably causing this issue.

The last working (installable through Steam) version is now 8.0-5.

**Comment by SaltyBet** [comment]
Thanks @Kaldaien and @Sangeki for your feedback.

I'll report this at DXVK's issue tracker.

**Comment by Sangeki** [comment]
> I'll report this at DXVK's issue tracker.

The issue is not with DXVK. It works just fine with Proton 8.0-5 and DXVK manually updated to the latest code.
The problem (whatever it actually is) is somewhere else in the Proton changes between 9.0-2 and 9.0-3.

The correct place to report this to, I think, would be the Proton github.

**Comment by SaltyBet** [comment]
Thanks for clarifying, @Sangeki.

I'll report there.

Cheers.

**Comment by SaltyBet** [comment]
Confirmed fixed.

Thanks a lot.

Cheers.
