### ISSUE TITLE
SK cannot run on Dead Rising Deluxe Remaster and crashes directly.

### ISSUE THREAD

**Issue by Kud-Fountain** [SpecialKO/SpecialK#205]
As title, the log is below.

[dxgi_budget.log](https://github.com/user-attachments/files/17129005/dxgi_budget.log)
[game_output.log](https://github.com/user-attachments/files/17129006/game_output.log)
[modules.log](https://github.com/user-attachments/files/17129007/modules.log)
[SpecialK.log](https://github.com/user-attachments/files/17129008/SpecialK.log)
[steam_api.log](https://github.com/user-attachments/files/17129009/steam_api.log)
[crash.log](https://github.com/user-attachments/files/17129010/crash.log)

**Comment by Kaldaien** [comment]
This looks like it might be caused by SteamAPI.

Try setting

```ini
[Steam.Log]
Silent=true
```

The game's never running its callbacks for some reason.

**Comment by Kud-Fountain** [comment]
> This looks like it might be caused by SteamAPI.
> 
> Try setting
> 
> ```ini
> [Steam.Log]
> Silent=true
> ```
> 
> The game's never running its callbacks for some reason.

Now it seems that there are no issues, thank you. I will close this issue now.
