### ISSUE TITLE
SK Crash at launch on Trails to Azure after update 24.10.5

### ISSUE THREAD

**Issue by shulymn** [SpecialKO/SpecialK#214]
Hello,

First Thanks Kaldaien for your work

I got the update for 24.10.5 today and went to play the game I'm playing these days : Legend of Heroes - Trails to Azure

The game freeze at launch. Tried hooking to the game after it launched, it freezes as well.
Tried to change silent=false to true, doesn't fix it either.
I rollbacked to 24.9.26 and it works again.

I tried the other Legend of Heroes games just to see if it crashes as well, in order of release : 
- Legend of Heroes - Trails in the Sky : Works
- Legend of Heroes - Trails in the Sky SC : Works
- Legend of Heroes - Trails in the Sky the 3rd : Works
- Legend of Heroes - Trails from Zero : Crash
- Legend of Heroes - Trails to Azure : Crash
- Legend of Heroes - Trails of Cold steel : Works
Didn't try the games released after

Here are the logs for Trails to Azure attached
I will be rolling back to 24.9.26 meanwhile

Thank you very much
[game_output.log](https://github.com/user-attachments/files/17350542/game_output.log)
[modules.log](https://github.com/user-attachments/files/17350543/modules.log)
[SpecialK.log](https://github.com/user-attachments/files/17350544/SpecialK.log)
[steam_api.log](https://github.com/user-attachments/files/17350545/steam_api.log)
[crash.log](https://github.com/user-attachments/files/17350546/crash.log)
[dxgi_budget.log](https://github.com/user-attachments/files/17350547/dxgi_budget.log)

I can also provide logs of the previous version to check for any difference if thats needed, feel free to ask !

**Comment by DJScias** [comment]
Can confirm crashes as well on your games (Zero, Azure, etc.) as well as the following too:
- Legend of Heroes - Trails of Cold Steel III
- Legend of Heroes - Trails of Cold Steel IV

They seem to happen when SK hits the cinematics and makes them become non-responsive. Happening for me on 24.10.19.1.

Rolling back to 24.9.26 also seems to fix my crashes with III and IV cinematics that I've noticed and makes them start up again (Just like Zero, Azure, etc all work again after rolling back).

**Comment by DJScias** [comment]
To add to the above, narrowed down these crashes starting as of 24.9.28.

The latest version that still works without crashing for these games is 24.9.27.1

**Comment by shulymn** [comment]
Thanks for the additional details

I have checked the changelog for 24.9.28, here is it : 

`24.9.28
=======
 + Overhauled input management for keybinds to better handle games with
     child/sibling windows (such as Metaphor's stupid exit confirmation)
 + Add hook on msvcp140.dll!_Thrd_sleep (...) because it may call directly
     into kernelbase.dll!SleepEx (...) instead of kernel32.dll.
 + Re-enable HID in Metaphor because it is required on SteamOS for gamepads.`

So my guess is something that happened here is causing the crashes, probably

**Comment by Kaldaien** [comment]
This problem, or at least the only one I could reproduce (Trails from Zero) should be fixed now.

```text
24.10.19.2
==========
 + Removed hook on msvcp140.dll!_Thrd_sleep(...) first introduced for Metaphor,
     because it causes problems with many of ph3's Legend of Heroes ports.
 + Removed internal injection blacklist on ApplicationFrameHost.exe.
 ```

[SpecialK.zip](https://github.com/user-attachments/files/17447006/SpecialK.zip)
https://github.com/SpecialKO/SpecialK/actions/runs/11420099381

**Comment by DJScias** [comment]
Can confirm from my own testing that Zero, Azure, Cold Steel 3 & 4 no longer have the (cinematic) crash issues in 24.10.19.2.

Hopefully that's the same for OP.

**Comment by shulymn** [comment]
Thanks Kaldaien

Can confirm it fixed the lauch issues on Trails to Azure and Trails from Zero !
