### ISSUE TITLE
Games crash when opening SK control panel if SteamAPI Integration is disabled

### ISSUE THREAD

**Issue by mzino** [SpecialKO/SpecialK#231]
This only applies starting from version 24.12.21.
Versions until 24.12.20.2 work fine.

When
```
[Steam.Log]
Silent=true
```
opening the SK control panel via CTRL+Shift+Backspace crashes the game to desktop. I tried with different games (e.g. SMTV, Devil May Cry 5, Metaphor) and it always crashes, so I assume it's not relevant to any specific game but to the SK UI.
Attaches is a SpecialK.log, as crash.log is empty.
[SpecialK.log](https://github.com/user-attachments/files/18218232/SpecialK.log)

**Comment by Kaldaien** [comment]
Should be fixed now.

```text
24.12.21.3
==========
 + Fixed recent change that would cause the control panel to crash in Steam games
     if Steam cloud is disabled or SteamAPI integration is turned off.
```
