### ISSUE TITLE
Diablo IV fails to pass the login screen with SK 24.12.28.1

### ISSUE THREAD

**Issue by mzino** [SpecialKO/SpecialK#234]
Local injection of version 24.12.28.1, Diablo IV (Steam) opens and when it reaches the login screen it fails with error "Code 1306" and stops responding until it crashes.

Works fine with the same exact setup until version 24.12.28, so it should be something introduced in https://github.com/SpecialKO/SpecialK/commit/3cf50d0eb4c84db7407374b5839a3649941833b0 or https://github.com/SpecialKO/SpecialK/commit/59ecaa07d4f7db66221eac42bea398c5d6703b69

I can reproduce it using the same .dll at different times so I exclude that it's a temporary server issue.

**Comment by Kaldaien** [comment]
I don't have time to install this game right now, can you test this build?

[SpecialK64.zip](https://github.com/user-attachments/files/18267647/SpecialK64.zip)

I suspect it's the dynamic spinlocks feature. I think there was a reason I didn't enable that in the past :)
