### ISSUE TITLE
Dungeon Keeper 2

### ISSUE THREAD

**Issue by Trass3r** [SpecialKO/SpecialK#35]
I got SpecialK+dgVoodoo basically working with DK2 (though it easily crashes inside d3d11.dll when you pan around).
<details>

```
   D3D11.DLL >            D3D11CoreCreateLayeredDevice
   D3D11.DLL >            D3D11CoreCreateLayeredDevice
 dinput8.dll >           D3D11_RSSetViewports_Override
 dinput8.dll >       D3D11Dev_CreateTexture2D_Override
 dinput8.dll >       D3D11Dev_CreateTexture2D_Override
 dinput8.dll >                   SK_ImGui_ControlPanel
 dinput8.dll >       SK_ImGui_InstallOpenCloseCallback
 dinput8.dll >                      SK_ImGui_DrawFrame
 dinput8.dll >                 ImGui_ImplDX11_NewFrame
```
</details>

In the live texture view when selecting 'All Textures' I even see some but `DumpOnFirstLoad=true` doesn't save anything but a single useless 1x1:
```
Dumped Name:    Uncompressed_E51A1896.dds
Texture:        e51a1896::e51a1896
Dimensions:     (1x1)
Format:         028 (DXGI_FORMAT_R8G8B8A8_UNORM)
MipLODs:        01
----------------
BindFlags:      0x0008
Usage:          0x0000
CPUAccessFlags: 0x00
Misc:           0x00
ArraySize:      01
```
 `AllowStaging` is on.

The logs show lots of
```
[DX11TexMgr] Impossible to cache texture (Code Origin: 'DDRAW.dll') -- Misc Flags: 0, MipLevels: 1, ArraySize: 1, CPUAccess: 0, BindFlags: Shader Resource, Render Target, Usage: Default, pInitialData: 00000000 (00000000)
[  D3D 11  ] CreateRTV, Format: DXGI_FORMAT_R8G8B8A8_UNORM
```
Probably cause of this line:
https://github.com/SpecialKO/SpecialK/blob/a47ce3a8a8fa2eea768d6a9553207e2f135472f0/src/render/d3d11/d3d11.cpp#L5517

**Comment by Aemony** [comment]
This doesn't seem doable, and using SK alongside dgVoodoo on top of texture dumping and injection will always be iffy and not really something officially supported. If it works, awesome, if it doesn't, well, then it doesn't.

Having spent some time with the GOG copy of this game, I have also come to the opinion that the game is (probably) best experienced without DX translation wrappers entirely. Using both GOG's custom DX wrapper as well as dgVoodoo seems to introduce insane pixelation on various textures, while also adding unexpected issues elsewhere (mouse sensitivity is out of whack for example).

I ended up just doing an LAA/4GB memory patch on `DKII.exe` and then running it in WinXP mode which ended up working the base.

Anyway, closing this ticket.
