### ISSUE TITLE
Arcania -Gothic 4

### ISSUE THREAD

**Issue by 64ghost** [SpecialKO/SpecialK#37]
Renamed the file to d3d9.dll . At startup Arcania.exe  error:

A required security module is not activated.
This program cannot be executed (8007).
See  http://www.securom.com/message.asp?m=module&c=8007&l=en for more details.

**Comment by 64ghost** [comment]
Ok. The game files have DFA.dll (SecuROM Data File Activation Library) but won't start without it.

**Comment by Aemony** [comment]
Closing as this is ultimately a DRM incompatibility, and while `DontHookWndProc=true` in the SK config file for the game might get past the error, it's ultimately not an incompatibility we can guarantee can be resolved since we tend to play nice with DRM solutions.
