### ISSUE TITLE
[Dying Light 2] Can't launch game.

### ISSUE THREAD

**Issue by lackesis** [SpecialKO/SpecialK#39]
log shows this.
[DLL Loader]   ( sl.common.dll                ) loaded '                      C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_805ccc89d82a60a4\_nvngx.dll' <LoadLibraryExW> { 'NVSDK_NGX_D3D11_Shutdown1' }

**Comment by Aemony** [comment]
Closing this as Dying Light 2 works fine with the latest version of Special K (v23.9.16.1 as of the time of writing) -- including when Streamline and Frame Generation is enabled.
