### ISSUE TITLE
ReShade64 local import broken

### ISSUE THREAD

**Issue by santarutaru** [SpecialKO/SpecialK#40]
Currently the work around is to rename existing
Reshade64.dll to dxgi.dll and SpecialK64.dll to d3d11.dll
or 
Reshade64.dll to d3d11.dll and SpecialK.dll to dxgi.dll

effectively enabling reshade to handle it's own hooking
instead of reshade importing anything. 

This work around is good so far for everyone except those 
who are experimenting with the Windows DXGI to DXVK swapchain.

As we are all looking forward to newer graphics being better implemented 
I hope this long known SK bug is revisited.

**Comment by Aemony** [comment]
This possibly broke when Special K got support for querying the location of Special K through the registry.

**Comment by Aemony** [comment]
The [SK wiki](https://wiki.special-k.info/en/SpecialK/ReShade) has updated instructions for how to set up Special K and ReShade alongside one another for maximum compatibility.
