### ISSUE TITLE
Local install create Profiles\AppCache in root folder of installation disk

### ISSUE THREAD

**Issue by AmeliaZ** [SpecialKO/SpecialK#41]
Local install create Profiles\AppCache in root folder of installation disk, with whatever localized or centralized profile.
It should save AppCache in `<path-to-SpecialK>\Profiles` or installation folder.

Version: 22.9.26

**Comment by Spodi** [comment]
Is this happening with specific games only, or all of them? Maybe you can narrow it down.

**Comment by Nicholas-Steel** [comment]
As far as I know, all games.

**Comment by AmeliaZ** [comment]
Plus, I see AppCache in my `<path-to-SpecialK>\Profiles`, the modification date is March 2022. Maybe this issue is only in versions after that?

**Comment by taki-eddine-47** [comment]
I'm having the same issue, but only with Steam games,

**Comment by Aemony** [comment]
It's a known issue that will hopefully be fixed once development continues later next year.

**Comment by Aemony** [comment]
This possibly broke when Special K got support for querying the location of Special K through the registry.

**Comment by Aemony** [comment]
This was fixed back in February as part of https://github.com/SpecialKO/SpecialK/pull/42.
