### ISSUE TITLE
How does Special K exactly spoof CPU cores?

### ISSUE THREAD

**Issue by Aetopia** [SpecialKO/SpecialK#44]
I am interested to know how Special K can spoof CPU cores.
I have checked `diagnostics\cpu.cpp`, but I can't find any function that sets the Spoofed CPU core amount.

Am I missing something?

**Comment by Aemony** [comment]
That file has three detoured Win32 APIs which SK manipulates the results of when called as part of the code in that file.

Games relying on those Win32 calls will get a spoofed return value with less cores than the system technically have.

**Comment by Kaldaien** [comment]
`GetLogicalProcessorInformation{Ex} (...)`

"Setting" the CPU count is not a thing with those APIs. They just read back an array of processors. Counting the number of processors involves walking through that array.
