### ISSUE TITLE
What does Sleepless Window thread actually do and how is it implemented?

### ISSUE THREAD

**Issue by Aetopia** [SpecialKO/SpecialK#45]
Reference: https://github.com/SpecialKO/SpecialK/blob/2575f70d0a2995cdc5fa9ef9bdd944f14a0cbb63/src/scheduler.cpp#L1026

As the name of the option, suggests it makes the Window Thread sleepless but in what sense? Additionally how is it implemented?

**Comment by Aemony** [comment]
Same way the CPU core spoofing was implemented — it detours some standard Win32 API calls and implements custom code/checks that manipulates the input (that being the game’s originally coded sleep duration) and executes Special K’s custom duration instead.

Any game that implements sleeping using the detoured API calls will end up running SK’s code instead, which allows us to skip the sleep call entirely or adjust it to our own liking.

**Comment by Kaldaien** [comment]
It replaces `Sleep (...)` calls on window threads with a wait function (`MsgWaitForMultipleObjects (...)`) that will wake up when there's a waiting message on the queue.
