### ISSUE TITLE
Steam Deck support?

### ISSUE THREAD

**Issue by opaintner** [SpecialKO/SpecialK#47]
Hello,
I have used SpecialK for a long time, mostly for both NieR:Automata and NieR:Replicant. I recently bought a steam deck, and because of its compatibility with games that natively run on Windows I was wondering if there was any way to apply SpecialK to a game within the Steam Deck's filesystem and get it to work so that I could reduce issues and improve performance and possibly battery life.

I have tried to do a manual install of SpecialK to NieR:Replicant, replacing the .exe with the older version as stated in the wiki and replacing `dxgi.dll` with SpecialK following the instructions in the wiki, except the `.dll` was not found in the game folder under `/home/.local/share/Steam/steamapps/common/<gamefolder>/dxgi.dll` and instead under `/home/.local/share/Steam/steamapps/compatdata/1113560/pfx/drive_c/windows/system32/dxgi.dll`, where `1113560` is the Steam ID for NieR:Replicant.

This proved to not work, even though it did boot correctly without Steam reporting that it had pulled the correct versions of the files. SpecialK did not appear whatsoever. Is there anything that can be done to make SpecialK work on a Steam Deck through Proton? If not, would there be anything in the works to maybe get it running? Thank you all for your time and assistance. 

Edit: I have taken a closer look at the README and noticed that SpecialK does run through Wine and DXVK, which I believe Proton uses, so I have a feeling this might have just been a matter of where the files are at.

**Comment by Aemony** [comment]
We don't officially support Steam Deck, which is why there's no instructions for how to set it up, but I know that other users had managed to set it up. I believe they typically do so through some separate cmd line argument or something that tells Wine/Proton to proxy load the specific SK DLL file instead of the Wine/Proton DLL file.

There's also a parameter that needs to be set in SK when using Wine to disable SK's use of some Windows calls that Wine doesn't implement.

```
[Compatibility.General]
UsingWINE=true
```

**Comment by QmwJlHuSg9pa** [comment]
> I have tried to do a manual install of SpecialK to NieR:Replicant, replacing the .exe with the older version as stated in the wiki and replacing `dxgi.dll` with SpecialK following the instructions in the wiki, except the `.dll` was not found in the game folder under `/home/.local/share/Steam/steamapps/common/<gamefolder>/dxgi.dll` and instead under `/home/.local/share/Steam/steamapps/compatdata/1113560/pfx/drive_c/windows/system32/dxgi.dll`, where `1113560` is the Steam ID for NieR:Replicant.

I haven't tested this with SpecialK, but try setting the following for a given Steam game.

Under "Properties" -> "General" -> "Launch Options": `WINEDLLOVERRIDES="dxgi=n,b" %command%`.
