### ISSUE TITLE
[Assassin's Creed Odyssey] cant launch game?

### ISSUE THREAD

**Issue by chuanki** [SpecialKO/SpecialK#53]
program crashes or keep loading in splashing image no matter which version (high, med or low or custom) i use, in the newest game ~v1.5.3~ v1.5.6

while if i launch SpecialK 10.3 it runs well, though no obvious change happened :O

**Comment by Nicholas-Steel** [comment]
The latest nightly release of Special K works fine with v1.5.6 of the game.

**Comment by chuanki** [comment]
> The latest nightly release of Special K works fine with v1.5.6 of the game.

the newest one with only 2 dlls for 1.65 now?

**Comment by Nicholas-Steel** [comment]
Yeah, **dxgi.dll** and **d3d11.dll**

**Comment by chuanki** [comment]
right? should be SpecialK32.dll and SpecialK64.dll?

**Comment by Nicholas-Steel** [comment]
I made a mistake, sorry. When you download the latest Special K you want to place the SpecialK64.dll file in the same place as the games EXE file and then rename it to either DXGI.dll or D3D11.dll

**Comment by chuanki** [comment]
thx!  thats what i forgot...  
and do you really see fps improvements?

**Comment by Nicholas-Steel** [comment]
With Special K? Naw, not really. DXVK offers a good performance increase though, for the DXVK mod you'll want to place both the 64bit DXGI.dll and D3D11.dll files in to the same place as the games EXE file.

https://github.com/doitsujin/dxvk/releases/download/v2.1/dxvk-2.1.tar.gz
https://github.com/doitsujin/dxvk/releases (if above URL is no longer the latest release)

**Comment by chuanki** [comment]
great i've  just been testing it too! that one really improves
i just tried a dxvk-for-windows version and it turns out good, giving only HDR not appliable, while for linux it says in the update log that HDR is supported, lol

**Comment by Aemony** [comment]
Closing this as AC: Odyssey works just fine with the latest version of Special K (v23.9.16.1 as of the time of writing).
