### ISSUE TITLE
[Mega Man Battle Network Legacy Collection] Dimming issues

### ISSUE THREAD

**Issue by marat569** [SpecialKO/SpecialK#62]
**Special K version:** Any

**Game:** Mega Man Battle Network Legacy Collection Vol. 1 + Mega Man Battle Network Legacy Collection Vol. 2 

**Summary:** For whatever reason, the game dims after gameplay with third party software injected into it; to the point where it becomes a black screen after ~20 minutes

**Suggested Behavior:** A fix has been found.  For `MMBN_LC1.exe` and `MMBN_LC2.exe` either have the compatibility profile as default to be 100% safe, or just these 4 lines would do as well. 

```
[Input.XInput]
Enable=false

[Textures.D3D11]
Cache=false

[Steam.Log]
Silent=true

[Window.System]
DontHookWndProc=true
```

_Note:_ The compatibility profile does not have `DontHookWndProc=true` -- so technically it would need to be the compatibility profile plus that setting 

**Conclusion:** Multiple users hop in the discord for the first time asking for help, only to be sent to change those settings. Having them as part of SpecialK's default would mitigate said user's issues, and they'd be able to enjoy the new legacy collection with SK!

**Comment by Aemony** [comment]
This have been solved in one of the newer versions of Special K currently in the Discord update channel.
