### ISSUE TITLE
Bright Memory: infinite crashed with Special K nullptr

### ISSUE THREAD

**Issue by stanlu1013** [SpecialKO/SpecialK#65]
Hello sir,

When launch this game (dx12 version) with Special K, i will got this error message.

Dx11 is normal, Dx12 will show this error meeaage.

Thanks!

Critical Assertion Failure: stagingFrame.fence.p != nullptr'
Source: ...\imgui_d3d12.cpp:1595

Game: Bright Memory: infinite
Special K Version: 23.6.7

Special K Error
https://i.imgur.com/ePU5hl6.png

UE4 Error
https://i.imgur.com/JujJ5Qd.png

**Comment by Spodi** [comment]
Are you trying to overwrite SwapChain settings with SK? Device removed was a common error, when this was still possible in dx12 via SKs GUI

**Comment by stanlu1013** [comment]
> Are you trying to overwrite SwapChain settings with SK? Device removed was a common error, when this was still possible in dx12 via SKs GUI

Hello sir,  sorry, do you mean this swapChain setting? I try to modify -1 to 0 but still get the same error.
Thanks!

https://i.imgur.com/0iimWPU.png

**Comment by Aemony** [comment]
> > Are you trying to overwrite SwapChain settings with SK? Device removed was a common error, when this was still possible in dx12 via SKs GUI
> 
> Hello sir, sorry, do you mean this swapChain setting? I try to modify -1 to 0 but still get the same error. Thanks!
> 
> https://i.imgur.com/0iimWPU.png

DX11 exposes more options in that section -- including overrides that are unsafe to apply in DX12.

I recommend removing the Special K config file for the game to reset the configuration, to ensure that the config file doesn't include any DX11 related overrides that it tries to enforce (and fail) on DX12.

**Comment by Aemony** [comment]
Solving issue ticket as I cannot reproduce this issue with the latest version of Special K.
