### ISSUE TITLE
[Feature Request] Support for AVIF screenshots with HDR metadata

### ISSUE THREAD

**Issue by Berny23** [SpecialKO/SpecialK#77]
There are a lot of reasons to drop JXR in favor of AVIF:
- JPEG-XR (JXR) has essentially been deprecated and superseded by AVIF (and JPEG-XL, but Google dropped support recently).
- [No current web browser](https://caniuse.com/jpegxr) and no image viewer except Windows Photos can show HDR content in JXR files, which is very unfortunate.
- AVIF has standardized HDR support and is usable in [most major web browsers](https://caniuse.com/avif) and more software than JXR.
- AVIF has much better compression than any other HDR image format (tested with libaom-av1)

Yes, it's me again, I asked about this format in Discord and Reddit already. I would try to implement it myself, but I have zero experience with DirectX/OpenGL/Vulkan.

**Comment by Aemony** [comment]
It's probably a bit wrong to claim JXR has been deprecated and superseeded by AVIF when JXR is inherently a Microsoft format and Microsoft Edge doesn't support AVIF, nor does Windows 10/11 make use of it for HDR screenshots either, or supports it natively in e.g. Windows Imaging Component (WIC) and probably other Windows low-level components.

**Comment by Berny23** [comment]
Ok, this is understandable. What about supporting AVIF _additionally_?

I mostly care about the lower file sizes (lossless).

**Comment by Kaldaien** [comment]
This already exists.

**Comment by spider623** [comment]
Hello from 2024, now windows 11 fully support avif 12 bit HDR, even in edge, also steam now uses AVIF for screenshots, any chance to get it in specialK?
