### ISSUE TITLE
Directive on the last line of `custom_SpecialK.ini` is set to false unconditionally in a particular scenario

### ISSUE THREAD

**Issue by blackwind** [SpecialKO/SpecialK#81]
[As noted on Discord](https://discord.com/channels/778539700981071872/778887425275199548/1144562964238712944), if `custom_SpecialK.ini` has Unix line endings, and there's a newline at the end of the file, the directive on the last line gets set to false no matter what. Presumably it's being read as "true\n", which isn't a valid boolean value, so Special K just sets it to false. If there isn't a newline at the end of the file or you switch to Windows line endings, the overrides work as expected. Because many editors default to Unix line endings and adding a newline at EOF, this is an edge case worth looking at with, presumably, a very simple solution since the bug doesn't affect `default_` and `master_` files.

**Comment by Kaldaien** [comment]
Thank you for pointing this out.

Yes, your observation is correct. `custom_*.ini` is an -imported- INI file, it basically appends the contents of that file on top of the normal INI file and merges them together.

`default_*` and `master_*` are base INI files, they're loaded like a normal INI file to establish default values or override existing ones.

The import function's had weird problems like this over the years, glad you pointed it out I'll see if I can get a proper fix for that.

**Comment by Kaldaien** [comment]
Fixed in 23.8.28.1
